FROM python:3.12-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

ENV APP_ENV=development
ENV PYTHONUNBUFFERED=1

# The worker needs to find the Celery app instance
# Command to run the Celery worker
CMD ["celery", "-A", "app.tasks.celery_app", "worker", "-l", "info", "--pool=solo"]